### ISSUE TITLE
"title" is missing ??!!

### ISSUE THREAD

**Issue by PvlD** [davedawkins/Feliz.Engine.Bulma#2]
![image](https://user-images.githubusercontent.com/10778065/138310635-7c9eda6e-3b53-4673-bb09-4517cc19bbf8.png)

**Comment by davedawkins** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/285421/138370895-6e86dceb-34bc-4c4c-877a-6dcbc0a5867f.png">

```fsharp
        bulma.title.h4Is4 "This is a Title 4"
```

**Comment by davedawkins** [comment]
Feliz.Engine.Bulma.1.0.0-beta-006 released with fix
